language: node_js
node_js: 6

branches:
  except:
  - gh-pages

script:
- npm test
- npm run-script docs
- '"$(npm bin)/gh-pages-travis"'

env:
  global:
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="docs"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="RWEDA Bot"
  - GIT_EMAIL="rwedabot@redwoodeda.com"

before_install:
- openssl aes-256-cbc -K $encrypted_2eb2d1086180_key -iv $encrypted_2eb2d1086180_iv
  -in id_rsa.enc -out id_rsa -d
